apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    compoent: web
  spec:
    containers:
      - name
        image: silefort/multi-client
        ports:
          - containerPort: 3000
